//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № п/п.
        /// </summary>
        public static string List1A {
            get {
                return ResourceManager.GetString("List1A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на №  и дата направления.
        /// </summary>
        public static string List1B {
            get {
                return ResourceManager.GetString("List1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Акт отбора образцов (номер, дата).
        /// </summary>
        public static string List1C {
            get {
                return ResourceManager.GetString("List1C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование продукции (образца).
        /// </summary>
        public static string List1D {
            get {
                return ResourceManager.GetString("List1D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование организации заказчика.
        /// </summary>
        public static string List1E {
            get {
                return ResourceManager.GetString("List1E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество образцов/масса/обьем.
        /// </summary>
        public static string List1F {
            get {
                return ResourceManager.GetString("List1F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер и дата акта о непригодности образцов (при наличии).
        /// </summary>
        public static string List1G {
            get {
                return ResourceManager.GetString("List1G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата поступления образцов.
        /// </summary>
        public static string List1H {
            get {
                return ResourceManager.GetString("List1H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрационный номер образца.
        /// </summary>
        public static string List1I {
            get {
                return ResourceManager.GetString("List1I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ФИО ответственного исполнителя, осуществляющего проведение испытаний.
        /// </summary>
        public static string List1J {
            get {
                return ResourceManager.GetString("List1J", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата выдачи образца ответственному исполнителю осуществляющего проведение испытаний.
        /// </summary>
        public static string List1K {
            get {
                return ResourceManager.GetString("List1K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата возврата образца после испытаний.
        /// </summary>
        public static string List1L {
            get {
                return ResourceManager.GetString("List1L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ф.И.О. сотрудника, внесшего запись.
        /// </summary>
        public static string List1M {
            get {
                return ResourceManager.GetString("List1M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Примечание.
        /// </summary>
        public static string List1N {
            get {
                return ResourceManager.GetString("List1N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер протокола.
        /// </summary>
        public static string List1O {
            get {
                return ResourceManager.GetString("List1O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вид продукции.
        /// </summary>
        public static string List1P {
            get {
                return ResourceManager.GetString("List1P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заявитель.
        /// </summary>
        public static string List1Q {
            get {
                return ResourceManager.GetString("List1Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изготовитель.
        /// </summary>
        public static string List1R {
            get {
                return ResourceManager.GetString("List1R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № п/п.
        /// </summary>
        public static string List2A {
            get {
                return ResourceManager.GetString("List2A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер протокола испытаний.
        /// </summary>
        public static string List2B {
            get {
                return ResourceManager.GetString("List2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата протокола испытаний.
        /// </summary>
        public static string List2C {
            get {
                return ResourceManager.GetString("List2C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № и дата направления.
        /// </summary>
        public static string List2D {
            get {
                return ResourceManager.GetString("List2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрационный номер образца.
        /// </summary>
        public static string List2E {
            get {
                return ResourceManager.GetString("List2E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер акта на списание (утилизацию)/возврата образцов.
        /// </summary>
        public static string List2F {
            get {
                return ResourceManager.GetString("List2F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата акта на списание (утилизацию)/возврата образцов.
        /// </summary>
        public static string List2G {
            get {
                return ResourceManager.GetString("List2G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата выдачи протокола испытаний.
        /// </summary>
        public static string List2H {
            get {
                return ResourceManager.GetString("List2H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ф.И.О. сотрудника, внесшего запись.
        /// </summary>
        public static string List2I {
            get {
                return ResourceManager.GetString("List2I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общество с ограниченной ответственностью «Испытательный Центр Вектор».
        /// </summary>
        public static string Org1EditJournalStartValue1 {
            get {
                return ResourceManager.GetString("Org1EditJournalStartValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Испытательный центр.
        /// </summary>
        public static string Org1EditJournalStartValue2 {
            get {
                return ResourceManager.GetString("Org1EditJournalStartValue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на «Журнал регистрации направлений и образцов 4».
        /// </summary>
        public static string Org1EditJournalStartValue3 {
            get {
                return ResourceManager.GetString("Org1EditJournalStartValue3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответственный за ведение журнала.
        /// </summary>
        public static string Org1EditJournalStartValue4_1 {
            get {
                return ResourceManager.GetString("Org1EditJournalStartValue4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата начала       « 09 »           января            2023 г..
        /// </summary>
        public static string Org1EditJournalStartValue4_2 {
            get {
                return ResourceManager.GetString("Org1EditJournalStartValue4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ФИО (подпись)*    Бузулуцкова С.А..
        /// </summary>
        public static string Org1EditJournalStartValue5_1 {
            get {
                return ResourceManager.GetString("Org1EditJournalStartValue5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата окончания «      »        2023 г..
        /// </summary>
        public static string Org1EditJournalStartValue5_2 {
            get {
                return ResourceManager.GetString("Org1EditJournalStartValue5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на *подпись только для журналов, ведущихся на бумажном носителе.
        /// </summary>
        public static string Org1EditJournalStartValue6 {
            get {
                return ResourceManager.GetString("Org1EditJournalStartValue6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 422527, РОССИЯ, РЕСП. ТАТАРСТАН, Зеленодольский Р-Н, ТЕР. ПРОМЫШЛЕННАЯПЛОЩАДКАИНДУСТРИАЛЬНЫЙПАРКМ7, ЗД. 8 
        ///Адрес (адреса) места (мест) осуществления деятельности:420000, РОССИЯ, Респ Татарстан, Зеленодольский р-н, муниципальный, сельское поселение Осиновское, территория ПромышленнаяПлощадкаИндустриальныйПаркМ7, здание 8/1, помещения 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34 ,35,36,37,38,51,52, 53,54,55,56,57,58,59 
        ///420000, РОССИЯ, Татарстан Респ, Зеленодо [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string Org1EditProtocolStartValue1 {
            get {
                return ResourceManager.GetString("Org1EditProtocolStartValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Иван Иванов.
        /// </summary>
        public static string Org1EditProtocolStartValue2 {
            get {
                return ResourceManager.GetString("Org1EditProtocolStartValue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 420000, РОССИЯ, Татарстан Респ, Зеленодольский р-н, Осиновское сельское поселение, территория промышленная площадка Индустриальный парк М7, здание 8
        ///420000, РОССИЯ, Респ Татарстан, Зеленодольский р-н, муниципальный, сельское поселение Осиновское, территория ПромышленнаяПлощадкаИндустриальныйПаркМ7, здание 8/1, помещения 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34 ,35,36,37,38,51,52, 53,54,55,56,57,58,59.
        /// </summary>
        public static string Org1EditProtocolStartValue3 {
            get {
                return ResourceManager.GetString("Org1EditProtocolStartValue3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Относительная влажность воздуха: (30-80) %, температура воздуха: (15-25) °С, атмосферное давление (630-800) мм.рт.ст., частота: (49,9-50,1) Гц, напряжение: (200-240) В..
        /// </summary>
        public static string Org1EditProtocolStartValue4 {
            get {
                return ResourceManager.GetString("Org1EditProtocolStartValue4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общество с ограниченной ответственностью.
        /// </summary>
        public static string Protocol1 {
            get {
                return ResourceManager.GetString("Protocol1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на УТВЕРЖДАЮ.
        /// </summary>
        public static string Protocol10 {
            get {
                return ResourceManager.GetString("Protocol10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Руководитель испытательного центра.
        /// </summary>
        public static string Protocol11 {
            get {
                return ResourceManager.GetString("Protocol11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ООО «Испытательный Центр Вектор».
        /// </summary>
        public static string Protocol12 {
            get {
                return ResourceManager.GetString("Protocol12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _______________Иванов Иван____________________.
        /// </summary>
        public static string Protocol13 {
            get {
                return ResourceManager.GetString("Protocol13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подпись  инициалы, фамилия.
        /// </summary>
        public static string Protocol14 {
            get {
                return ResourceManager.GetString("Protocol14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _________________________14.09.2029_______________.
        /// </summary>
        public static string Protocol15 {
            get {
                return ResourceManager.GetString("Protocol15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата утверждения.
        /// </summary>
        public static string Protocol16 {
            get {
                return ResourceManager.GetString("Protocol16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на М.П..
        /// </summary>
        public static string Protocol17 {
            get {
                return ResourceManager.GetString("Protocol17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРОТОКОЛ ИСПЫТАНИЙ.
        /// </summary>
        public static string Protocol18 {
            get {
                return ResourceManager.GetString("Protocol18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Число страниц:.
        /// </summary>
        public static string Protocol19 {
            get {
                return ResourceManager.GetString("Protocol19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на «Испытательный Центр Вектор».
        /// </summary>
        public static string Protocol2 {
            get {
                return ResourceManager.GetString("Protocol2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрационный (условный) номер, характеристика испытуемого образца:.
        /// </summary>
        public static string Protocol20 {
            get {
                return ResourceManager.GetString("Protocol20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата получения образца:.
        /// </summary>
        public static string Protocol21 {
            get {
                return ResourceManager.GetString("Protocol21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Место проведения испытаний: 420000, РОССИЯ, Татарстан Респ, Зеленодольский р-н, Осиновское сельское поселение, территория промышленная площадка Индустриальный парк М7, здание 8
        ///420000, РОССИЯ, Респ Татарстан, Зеленодольский р-н, муниципальный, сельское поселение Осиновское, территория ПромышленнаяПлощадкаИндустриальныйПаркМ7, здание 8/1, помещения 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34 ,35,36,37,38,51,52, 53,54,55,56,57,58,59.
        /// </summary>
        public static string Protocol22 {
            get {
                return ResourceManager.GetString("Protocol22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сведения о заказчике:.
        /// </summary>
        public static string Protocol23 {
            get {
                return ResourceManager.GetString("Protocol23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сведения об изготовителе:.
        /// </summary>
        public static string Protocol24 {
            get {
                return ResourceManager.GetString("Protocol24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Реквизиты сопроводительного документа:.
        /// </summary>
        public static string Protocol25 {
            get {
                return ResourceManager.GetString("Protocol25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обозначения и наименования нормативных документов, устанавливающих методы испытаний:.
        /// </summary>
        public static string Protocol26 {
            get {
                return ResourceManager.GetString("Protocol26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сведения об отборе образцов: Образец(ы) предоставлен(ы) заказчиком;.
        /// </summary>
        public static string Protocol27 {
            get {
                return ResourceManager.GetString("Protocol27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Реквизиты акта отбора образцов (при необходимости)-.
        /// </summary>
        public static string Protocol28 {
            get {
                return ResourceManager.GetString("Protocol28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Даты проведения испытаний: .
        /// </summary>
        public static string Protocol29 {
            get {
                return ResourceManager.GetString("Protocol29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес места нахождения юридического лица:.
        /// </summary>
        public static string Protocol3 {
            get {
                return ResourceManager.GetString("Protocol3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Условия проведения испытаний: .
        /// </summary>
        public static string Protocol30 {
            get {
                return ResourceManager.GetString("Protocol30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Относительная влажность воздуха: (30-80) %, температура воздуха: (15-25) °С, атмосферное давление (630-800) мм.рт.ст., частота: (49,9-50,1) Гц, напряжение: (200-240) В..
        /// </summary>
        public static string Protocol31 {
            get {
                return ResourceManager.GetString("Protocol31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительная информация:.
        /// </summary>
        public static string Protocol32 {
            get {
                return ResourceManager.GetString("Protocol32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание! Результаты испытаний, зафиксированные в протоколе, относятся только к образцам, предоставленным заказчиком и подвергнутым испытаниям. Испытательная лаборатория не несет ответственности за информацию, предоставленную заказчиком. Протокол испытаний не может быть воспроизведен частично или полностью без письменного разрешения лаборатории..
        /// </summary>
        public static string Protocol33 {
            get {
                return ResourceManager.GetString("Protocol33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В случаях, если необходимость выдачи заключений о соответствии и правило принятия решения приведено в методе испытаний, заявления о соответствии требованиям или спецификации приведены в разделе «Результаты испытаний». В иных случаях, в выдаче заявлений о соответствии нет необходимости..
        /// </summary>
        public static string Protocol34 {
            get {
                return ResourceManager.GetString("Protocol34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конец протокола испытаний.
        /// </summary>
        public static string Protocol35 {
            get {
                return ResourceManager.GetString("Protocol35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результаты испытаний:.
        /// </summary>
        public static string Protocol36 {
            get {
                return ResourceManager.GetString("Protocol36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № п/п.
        /// </summary>
        public static string Protocol37 {
            get {
                return ResourceManager.GetString("Protocol37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Определяемый показатель, единица измерения.
        /// </summary>
        public static string Protocol38 {
            get {
                return ResourceManager.GetString("Protocol38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на НД на методы испытаний.
        /// </summary>
        public static string Protocol39 {
            get {
                return ResourceManager.GetString("Protocol39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 422527, РОССИЯ, РЕСП. ТАТАРСТАН, Зеленодольский Р-Н, ТЕР. ПРОМЫШЛЕННАЯПЛОЩАДКАИНДУСТРИАЛЬНЫЙПАРКМ7, ЗД. 8.
        /// </summary>
        public static string Protocol4 {
            get {
                return ResourceManager.GetString("Protocol4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средства измерения/испытательное оборудование.
        /// </summary>
        public static string Protocol40 {
            get {
                return ResourceManager.GetString("Protocol40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПДК и нормы
        ///(при необходимости).
        /// </summary>
        public static string Protocol41 {
            get {
                return ResourceManager.GetString("Protocol41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результаты испытаний.
        /// </summary>
        public static string Protocol42 {
            get {
                return ResourceManager.GetString("Protocol42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес (адреса) места (мест) осуществления деятельности:420000, РОССИЯ, Респ Татарстан, Зеленодольский р-н, муниципальный, сельское поселение Осиновское, территория ПромышленнаяПлощадкаИндустриальныйПаркМ7, здание 8/1, помещения 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34 ,35,36,37,38,51,52, 53,54,55,56,57,58,59.
        /// </summary>
        public static string Protocol5 {
            get {
                return ResourceManager.GetString("Protocol5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 420000, РОССИЯ, Татарстан Респ, Зеленодольский р-н, Осиновское сельское поселение, территория промышленная площадка Индустриальный парк М7, здание 8.
        /// </summary>
        public static string Protocol6 {
            get {
                return ResourceManager.GetString("Protocol6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уникальный номер записи об аккредитации в реестре аккредитованных лиц № RA.RU.21ОМ79 от 28.03.2022.
        /// </summary>
        public static string Protocol7 {
            get {
                return ResourceManager.GetString("Protocol7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на телефон: +7 9299752698.
        /// </summary>
        public static string Protocol8 {
            get {
                return ResourceManager.GetString("Protocol8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на e-mail: icvektor@bk.ru.
        /// </summary>
        public static string Protocol9 {
            get {
                return ResourceManager.GetString("Protocol9", resourceCulture);
            }
        }
    }
}
