//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № п/п.
        /// </summary>
        public static string List1A {
            get {
                return ResourceManager.GetString("List1A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на №  и дата направления.
        /// </summary>
        public static string List1B {
            get {
                return ResourceManager.GetString("List1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Акт отбора образцов (номер, дата).
        /// </summary>
        public static string List1C {
            get {
                return ResourceManager.GetString("List1C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование продукции (образца).
        /// </summary>
        public static string List1D {
            get {
                return ResourceManager.GetString("List1D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование организации заказчика.
        /// </summary>
        public static string List1E {
            get {
                return ResourceManager.GetString("List1E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество образцов/масса/обьем.
        /// </summary>
        public static string List1F {
            get {
                return ResourceManager.GetString("List1F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер и дата акта о непригодности образцов (при наличии).
        /// </summary>
        public static string List1G {
            get {
                return ResourceManager.GetString("List1G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата поступления образцов.
        /// </summary>
        public static string List1H {
            get {
                return ResourceManager.GetString("List1H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрационный номер образца.
        /// </summary>
        public static string List1I {
            get {
                return ResourceManager.GetString("List1I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ФИО ответственного исполнителя, осуществляющего проведение испытаний.
        /// </summary>
        public static string List1J {
            get {
                return ResourceManager.GetString("List1J", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата выдачи образца ответственному исполнителю осуществляющего проведение испытаний.
        /// </summary>
        public static string List1K {
            get {
                return ResourceManager.GetString("List1K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата возврата образца после испытаний.
        /// </summary>
        public static string List1L {
            get {
                return ResourceManager.GetString("List1L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ф.И.О. сотрудника, внесшего запись.
        /// </summary>
        public static string List1M {
            get {
                return ResourceManager.GetString("List1M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Примечание.
        /// </summary>
        public static string List1N {
            get {
                return ResourceManager.GetString("List1N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер протокола.
        /// </summary>
        public static string List1O {
            get {
                return ResourceManager.GetString("List1O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вид продукции.
        /// </summary>
        public static string List1P {
            get {
                return ResourceManager.GetString("List1P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заявитель.
        /// </summary>
        public static string List1Q {
            get {
                return ResourceManager.GetString("List1Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изготовитель.
        /// </summary>
        public static string List1R {
            get {
                return ResourceManager.GetString("List1R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № п/п.
        /// </summary>
        public static string List2A {
            get {
                return ResourceManager.GetString("List2A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер протокола испытаний.
        /// </summary>
        public static string List2B {
            get {
                return ResourceManager.GetString("List2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата протокола испытаний.
        /// </summary>
        public static string List2C {
            get {
                return ResourceManager.GetString("List2C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № и дата направления.
        /// </summary>
        public static string List2D {
            get {
                return ResourceManager.GetString("List2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрационный номер образца.
        /// </summary>
        public static string List2E {
            get {
                return ResourceManager.GetString("List2E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер акта на списание (утилизацию)/возврата образцов.
        /// </summary>
        public static string List2F {
            get {
                return ResourceManager.GetString("List2F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата акта на списание (утилизацию)/возврата образцов.
        /// </summary>
        public static string List2G {
            get {
                return ResourceManager.GetString("List2G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата выдачи протокола испытаний.
        /// </summary>
        public static string List2H {
            get {
                return ResourceManager.GetString("List2H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ф.И.О. сотрудника, внесшего запись.
        /// </summary>
        public static string List2I {
            get {
                return ResourceManager.GetString("List2I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общество с ограниченной ответственностью «Испытательный Центр Вектор».
        /// </summary>
        public static string Org1EditJournalStartValue1 {
            get {
                return ResourceManager.GetString("Org1EditJournalStartValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Испытательный центр.
        /// </summary>
        public static string Org1EditJournalStartValue2 {
            get {
                return ResourceManager.GetString("Org1EditJournalStartValue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на «Журнал регистрации направлений и образцов 4».
        /// </summary>
        public static string Org1EditJournalStartValue3 {
            get {
                return ResourceManager.GetString("Org1EditJournalStartValue3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответственный за ведение журнала.
        /// </summary>
        public static string Org1EditJournalStartValue4_1 {
            get {
                return ResourceManager.GetString("Org1EditJournalStartValue4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата начала       « 09 »           января            2023 г..
        /// </summary>
        public static string Org1EditJournalStartValue4_2 {
            get {
                return ResourceManager.GetString("Org1EditJournalStartValue4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ФИО (подпись)*    Бузулуцкова С.А..
        /// </summary>
        public static string Org1EditJournalStartValue5_1 {
            get {
                return ResourceManager.GetString("Org1EditJournalStartValue5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата окончания «      »        2023 г..
        /// </summary>
        public static string Org1EditJournalStartValue5_2 {
            get {
                return ResourceManager.GetString("Org1EditJournalStartValue5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на *подпись только для журналов, ведущихся на бумажном носителе.
        /// </summary>
        public static string Org1EditJournalStartValue6 {
            get {
                return ResourceManager.GetString("Org1EditJournalStartValue6", resourceCulture);
            }
        }
    }
}
